# Generated by Django 4.1.1 on 2022-09-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0003_reviews_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
